### ISSUE TITLE
empty GT or pred

### ISSUE THREAD

**Issue by chensonglu** [bes-dev/mean_average_precision#5]
Thanks for your great job. However, when GTs or preds are empty, there is an error.

**Comment by bes-dev** [comment]
@chensonglu thanks for your feedback. Provide reproducer, please

**Comment by chensonglu** [comment]
I solve this problem in a dirty way. I assume that the format of GT is correct and GT must exist. So when preds are empty, just skip it.
![image](https://user-images.githubusercontent.com/5317029/88526013-f9b95580-d02d-11ea-98ba-7156fcc4b0da.png)

**Comment by chensonglu** [comment]
Maybe the format check "assert" can be set as a warning, not as an error. Coders must assure the format of GTs and preds are correct by themselves.

**Comment by chensonglu** [comment]
Maybe this way is better. It can check GTs. When preds are null, it can be set as an empty np.array([]), so preds.ndim == 1.
![image](https://user-images.githubusercontent.com/5317029/88527082-5ec17b00-d02f-11ea-93b9-7bb8be0173da.png)

**Comment by bes-dev** [comment]
@chensonglu preds and gt must have ndims = 2 because after that we make slice by second dim (it will be failed if we make slice by unavailable dim). 

What we should do, if we get preds as 1-dimensional array that is not empty? 

Anyway, input data should exactly match to expected format and we check it. I'll think how it can be improved, bu currently user can handle it on thier side, using simple adapter function (that add missing fields, convert empty array to np.zeros(0, 6), etc.). Also, user can use 'try except' to check, that there aren't any exceptions.

**Comment by michael-camilleri** [comment]
I also would like a fix to this. Specifically, if I add an array of zeros, that will skew results as an incorrect detection, but I would like to treat this as a missing detection (False negative) rather.

**Comment by bes-dev** [comment]
The library now supports empty preds or gt. You can use this feature from develop branch (it will be added at the next release).

**Comment by michael-camilleri** [comment]
Thanks!
